package com.horizon.matemticascurso

sealed class AppScreens (val route: String) {
    object loginScreen: AppScreens("login Screen")
    object splashScreenRoute : AppScreens("Splash Screen")
    object favoriteScreen : AppScreens("favorites screen")
    object homeScreenRoute: AppScreens("HomeScreenRoute")
    object basicOperation: AppScreens("Basic operation")
    object basicOperationTwo: AppScreens("Basic Operation two")
    object simplificacionScreen: AppScreens("Simplificación")
    object transformEcua: AppScreens("TransformacionEcua")
    object transformEcuaTwo:AppScreens("Tranformaciónde ecuaciones")
    object leyExpoOne: AppScreens("Leyes de los exponentes SessionOne")
    object leyExpoTwo: AppScreens("Ley de los exponentes SessionTwo")
    object leyExpoThree: AppScreens("Ley de los exponenetes SessionThree")
    object multiPoliOne: AppScreens("Multiplicación de polinomios SessionOne")
    object multiPoliTwo: AppScreens("Multiplicación de polinomios SessionTwo")
    object multiPoliThree: AppScreens("Multiplicación de polinomios SessionThree")
    object simpli2One: AppScreens("simplificacion 2 SessionOne")
    object simpli2Two: AppScreens("simplificacion 2 SessionTwo")
    object simpli2Three: AppScreens("simplificacion 2 SessionThree")
    object ecuaLineales: AppScreens("Ecuaciones lineales")
    object puntosDePlanoOne: AppScreens("Puntos de un plano SessionOne")
    object punPlanoTwo: AppScreens("Puntos de un plano SessionTwo")
    object punPlaThree: AppScreens("Puntos de un plano SessionThree")
    object grafiRectaOne: AppScreens("Gráfica de la recta SessionOne")
    object grafiRectaTwo: AppScreens("Gráfica de la recta SessionTwo")
    object grafiRectaThree: AppScreens("Gráfica de la recta SessionThree")
    object sitemaEcua1: AppScreens("Sistema de ecuaciones 1 SessionOne")
    object sistemEcua1Two: AppScreens("sistema de ecua lineales 1 SessionTwo")
    object sistemEcua1Three: AppScreens("sistema de ecua lineales 1 SessionThree")
    object sistemaEcua2: AppScreens("Sistema de ecuaciones 2 SessionOne")
    object sistemaEcua2Two: AppScreens("Sistema de ecuaciones 2 SessionTwo")
    object sistemaEcua2Three: AppScreens("Sistema de ecuaciones 2 SessionThree")
    object desigualLineales: AppScreens("Desigualdades lineales SessionOne")
    object desigualLinealesTwo: AppScreens("Desigualdades lineales SessionTwo")
    object desigualLinealesThree: AppScreens("Desigualdades lineales SessionThree")
    object producNotaOne: AppScreens("Productos notables SessionOne")
    object producNotaTwo: AppScreens("Productos notables SessionTwo")
    object producNotaThree: AppScreens("Productos notables SessionThree")
    object facto1One: AppScreens("Factorización 1 SessionOne")
    object facto1Two: AppScreens("Factorización 1 SessionTwo")
    object facto1Three: AppScreens("Factorización 1 SessionThree")
    object facto2One: AppScreens("Factorización 2 SessionOne")
    object facto2Two: AppScreens("Factorización 2 SessionTwo")
    object facto2Three: AppScreens("Factorización 2 SessionThree")
    object facto3One: AppScreens("Factorización 3 SessionOne")
    object facto3Two: AppScreens("Factorización 3 SessionTwo")
    object facto3Three: AppScreens("Factorización 3 SessiomThree")
    object raices: AppScreens("raíces")
    object raizTwo: AppScreens("raíz SessionTwo")
    object numIrracionales: AppScreens("números irracionales")
    object sistemaEcua3: AppScreens("Sistema de ecuaciones 3")
    object desarrolloPoli: AppScreens("Desarrollo de polinomios")
}